namespace SprintForge.Domain.Planning;

public enum WorkItemKind { Epic, Story, Task, Subtask, Bug, Spike }
public enum WorkItemType { Dev, Test, Doc, Review, Deploy, Design }

/// <summary>A single work item generated by the Sprint Planner, ready for Jira creation.</summary>
public sealed record WorkItem
{
    public required string LocalId { get; init; }
    public string? ParentLocalId { get; init; }
    public required WorkItemKind Kind { get; init; }
    public WorkItemType? Type { get; init; }
    public required string Summary { get; init; }
    public string? Description { get; init; }
    public string? AcceptanceCriteria { get; init; }
    public required decimal EstimateDays { get; init; }
    public int? StoryPoints { get; init; }
    public string? Assignee { get; init; }
    public string? EpicKey { get; init; }
    public IReadOnlyList<string> Labels { get; init; } = [];
    public IReadOnlyList<string> Components { get; init; } = [];

    /// <summary>Set after Jira creation is approved and executed.</summary>
    public string? JiraKey { get; init; }

    /// <summary>True if this item's estimate exceeds the configured dev-day budget — triggers a validation warning.</summary>
    public bool ExceedsBudget { get; init; }
}

/// <summary>Sprint metadata parsed from the import source.</summary>
public sealed record SprintCalendar
{
    public required string SprintName { get; init; }
    public required DateOnly StartDate { get; init; }
    public required DateOnly EndDate { get; init; }
    public required int DurationDays { get; init; }
    public required int DevelopmentDays { get; init; }
    public required int BufferDays { get; init; }
    public required int WorkingHoursPerDay { get; init; }
    public IReadOnlyList<DateOnly> Holidays { get; init; } = [];
    public required int CapacityPoints { get; init; }
}
